Repository cd-carpe-diem/Carpe-Diem-FE, pull requests merged in 2023-03, with the labels that each got.

#56 Design: 마이페이지 디자인 수정
  src/views/Contents/MyContent/FriendContent.tsx
  src/views/MyPage/Edit.tsx
  src/views/MyPage/Friend/Friend.css
  src/views/MyPage/Friend/Friend.tsx
  src/views/MyPage/Receive.tsx
  src/views/MyPage/Send.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
  yarn.lock
Labels: 💄 Design, 😀 Merge Develop

#57 Fix: 페이지네이션-카드(무한 스크롤) Redux로 수정
  src/redux/reducer/cardReducer.ts
  src/redux/saga/cardSaga.ts
  src/views/Video/Video.tsx
Labels: 🐛 Fix, 😀 Merge Develop

#58 Feat: 페이지네이션-앨범(무한 스크롤 추가)
  src/redux/reducer/albumReducer.ts
  src/redux/saga/albumSaga.ts
  src/views/Library/Library.tsx
Labels: ✨ Feat, 😀 Merge Develop

#60 Feat: 비디오탭 필터링 컴포넌트 분리, 앨범 생성 컴포넌트 수정
  src/redux/reducer/cardReducer.ts
  src/redux/saga/cardSaga.ts
  src/redux/types.ts
  src/styles/App.css
  src/views/Album/Share.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
  yarn.lock
Labels: 💄 Design, ✨ Feat

#59 Feat: 앨범 삭제, 수정(client)
  package.json
  src/App.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/Headers.css
  src/components/MainLayout/MainLayout.tsx
  src/components/Sidebar/Profile/Profile.tsx
  src/components/Sidebar/Sidebar.tsx
  src/views/Album/SingleAlbum.tsx
  src/views/Album/SingleAlbumCarousel.tsx
  src/views/Album/SingleAlbumDelete.tsx
  src/views/Album/SingleAlbumEdit.tsx
  src/views/Album/SingleVideo.tsx
  src/views/Album/StyleSingleAlbum.css
  src/views/Camera/MobileCamera.tsx
  src/views/Contents/AlbumContent/SingleAlbumContent.jsx
  src/views/Contents/AlbumContent/SingleVideoContent.tsx
  src/views/Contents/CamContent/CamContent.tsx
  src/views/Contents/LibraryContent/LibraryContent.tsx
  src/views/Contents/MyContent/EditContent.tsx
  src/views/Contents/PageContent/PageContent.tsx
  src/views/Contents/VideoContent/VideoContent.tsx
  src/views/FriendAlbum/AlbumCarousel.tsx
  src/views/MyPage/Edit.tsx
  src/views/MyPage/Friend/index.html
  src/views/Page/Page.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
  src/views/Video/Video2.tsx
Labels: ✨ Feat, 🐛 Fix

#61 Fix: 친구 요청 유효성 검사
  src/views/MyPage/Friend/Friend.tsx
  src/views/MyPage/Receive.tsx
  src/views/MyPage/Send.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
Labels: ♻️ Refactor, 🐛 Fix, 😀 Merge Develop

#62 Design: 공통 컴포넌트 적용
  package.json
  public/imgs/btn-google-signin-light-normal-web@2x.png
  public/imgs/main-logo-dark.png
  public/imgs/main-logo-white.png
  public/imgs/mask.jpg
  src/App.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/Headers.css
  src/components/MainLayout/MainLayout.tsx
  src/components/Sidebar/Profile/Profile.tsx
  src/components/Sidebar/Sidebar.tsx
  src/redux/reducer/cardReducer.ts
  src/redux/saga/cardSaga.ts
  src/redux/types.ts
  src/styles/App.css
  src/types/cam.d.ts
  src/views/Album/Share.tsx
  src/views/Album/SingleAlbum.tsx
  src/views/Album/SingleAlbumCarousel.tsx
  src/views/Album/SingleAlbumDelete.tsx
  src/views/Album/SingleAlbumEdit.tsx
  src/views/Album/SingleVideo.tsx
  src/views/Album/StyleSingleAlbum.css
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Card/InteractiveCard.tsx
  src/views/Contents/AlbumContent/SingleAlbumContent.jsx
  src/views/Contents/AlbumContent/SingleVideoContent.tsx
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Contents/CamContent/WebCamContent.tsx
  src/views/Contents/LibraryContent/LibraryContent.tsx
  src/views/Contents/MyContent/EditContent.tsx
  src/views/Contents/MyContent/FriendContent.tsx
  src/views/Contents/PageContent/PageContent.tsx
  src/views/Contents/VideoContent/VideoContent.tsx
  src/views/FriendAlbum/AlbumCarousel.tsx
  src/views/FriendAlbum/SingleAlbum.tsx
  src/views/Library/Library.tsx
  src/views/Main/main.css
  src/views/Main/main.tsx
  src/views/MyPage/Edit.tsx
  src/views/MyPage/Friend/Friend.tsx
  src/views/MyPage/Friend/FriendItem.tsx
  src/views/MyPage/Friend/index.html
  src/views/MyPage/Receive.tsx
  src/views/MyPage/Send.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
  src/views/Page/Page.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
  src/views/Video/Video2.tsx
  yarn.lock
Labels: 💄 Design

#64 Design: 전체 모달 창 수정
  .gitignore
  src/views/Album/SingleAlbumCarousel.tsx
  src/views/Contents/FriendLibraryContent/FriendLibraryContent.tsx
  src/views/FriendAlbum/SingleAlbum.tsx
  src/views/FriendLibrary/FriendLibrary.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
  src/views/Video/Video.tsx
  yarn.lock
Labels: 💄 Design, 🐛 Fix

#66 Fix: 최근 영상 잘못된 시간 수정(camera/web, camera/mobile)
  src/App.tsx
  src/views/Card/InteractiveCard.tsx
Labels: 🐛 Fix, 😀 Merge Develop

#68 Design: 디자인 요소 수정
  src/components/Header/Header.tsx
  src/redux/reducer/authReducer.ts
  src/redux/saga/authSaga.ts
  src/redux/types.ts
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/Modal.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Card/InteractiveCard.tsx
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Contents/CamContent/WebCamContent.tsx
  src/views/Main/main.tsx
  src/views/Video/VideoDelete.tsx
Labels: ✨ Feat, 🐛 Fix

#69 Design: 헤더 아이콘 추가
  src/common/constraints.ts
  src/components/Header/Header.tsx
  src/views/Camera/MobileCamera.tsx
Labels: 💄 Design, 🧹Chore

#70 Feat: 감정 리포트
  src/App.tsx
  src/components/Header/Header.tsx
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/Emotion/EmotionLineChart.tsx
  src/views/Emotion/EmotionPieChart.tsx
Labels: ✨ Feat, 😀 Merge Develop

#72 Feat,Fix: 실시간 차트 색상 추가, 썸네일 시간 수정
  src/views/Camera/Emotion.tsx
  src/views/Camera/EmotionSetData.ts
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/WebCamera.tsx
Labels: 💄 Design, ✨ Feat, 🐛 Fix, 😀 Merge Develop

#73 Design: 웹캠 페이지, 필터링 디자인 수정
  package.json
  public/imgs/browser-frame.png
  public/imgs/imac-frame.png
  src/components/Header/Header.tsx
  src/views/Camera/Emotion.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Camera/index.css
  src/views/Contents/CamContent/WebCamContent.tsx
  src/views/Main/main.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
Labels: 💄 Design

#74 Chore: 배포 프록시 설정
  package.json
  src/config/index.ts
  src/index.tsx
  src/redux/saga/albumSaga.ts
  src/redux/saga/authSaga.ts
  src/redux/saga/cardSaga.ts
  src/redux/saga/friendAlbumSaga.ts
  src/services/Cam/uploadToS3Bucket.ts
  src/views/Album/SingleVideo.tsx
  src/views/Auth/index.tsx
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/Modal.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Contents/CamContent/WebCamContent.tsx
  src/views/FriendAlbum/SingleAlbum.tsx
  src/views/FriendLibrary/FriendLibrary.tsx
  src/views/Library/BookButton.tsx
  src/views/Login/Login.tsx
  src/views/Main/main.tsx
  src/views/MyPage/Edit.tsx
  src/views/MyPage/Friend/Friend.tsx
  src/views/MyPage/Receive.tsx
  src/views/MyPage/Send.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
  src/views/Video/Video2.tsx
  src/views/Video/Video3.tsx
Labels: 🧹Chore

#75 Fix: 감정 리포트 데이터 연결
  src/views/Camera/Emotion.tsx
  src/views/Emotion/EmotionLineChart.tsx
  src/views/Emotion/EmotionPieChart.tsx
Labels: 💄 Design, 🐛 Fix, 😀 Merge Develop

#76 Design: 감정리포트 및 여러 페이지 수정
  public/imgs/browser-frame.png
  public/imgs/not_found_files.jpg
  src/App.tsx
  src/assets/iphone.png
  src/components/Header/Header.tsx
  src/config/index.ts
  src/index.tsx
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/Emotion/EmotionLineChart.tsx
  src/views/Emotion/EmotionPieChart.tsx
  src/views/FriendLibrary/FriendLibrary.tsx
  src/views/Main/main.tsx
  src/views/Video/Video.tsx
Labels: 💄 Design, 🐛 Fix

#77 Feat: 감정리포트 이메일 공유
  package.json
  src/views/Album/Share.tsx
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/Emotion/Share.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
  src/views/Video/VideoDetail.tsx
Labels: 💄 Design, ✨ Feat

#78 Fix: 감정 리포트 데이터 연결, 시간, 위치 수정
  public/imgs/imac-frame.png
  src/views/Camera/Emotion.tsx
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Card/InteractiveCard.tsx
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/Emotion/EmotionLineChart.tsx
  src/views/Emotion/EmotionPieChart.tsx
  src/views/Video/Video.tsx
Labels: 🐛 Fix, 😀 Merge Develop

#80 Design: mobile&cam 페이지 수정
  src/assets/iphone-frame.png
  src/components/Header/Header.tsx
  src/views/Album/SingleAlbumCarousel.tsx
  src/views/Album/SingleAlbumDelete.tsx
  src/views/Album/SingleAlbumEdit.tsx
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Camera/index.css
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Contents/CamContent/WebCamContent.tsx
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/Contents/MyContent/FriendContent.tsx
  src/views/Library/Book.tsx
  src/views/Library/Library.tsx
  src/views/Video/Video.tsx
Labels: 💄 Design, 🐛 Fix, 😀 Merge Develop

#82 마이페이지 수정
  src/views/MyPage/Edit.tsx
Labels: ✨ Feat

#84 Fix: 마이페이지 수정
  src/views/MyPage/Edit.tsx
Labels: 🐛 Fix

#83 Feat/cd 174
  src/views/MyPage/Edit.tsx
Labels: 😀 Merge Develop

#85 Design: 작은 디자인 요소들 수정
  src/App.tsx
  src/components/Header/Header.tsx
  src/services/Cam/uploadToS3Bucket.ts
  src/types/cam.d.ts
  src/views/Auth/index.tsx
  src/views/Button/OffButtons.jsx
  src/views/Button/OnButtons.jsx
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Camera/index.css
  src/views/Contents/VideoContent/VideoContent.tsx
  src/views/MyPage/Edit.tsx
  src/views/Video/VideoDetail.tsx
Labels: 💄 Design, 🐛 Fix

#87 Design: mobilecam canvas 조정
  src/components/Header/Header.tsx
  src/views/Album/SingleAlbumCarousel.tsx
  src/views/Album/SingleAlbumEdit.tsx
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Camera/index.css
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/FriendLibrary/Book.tsx
  src/views/Library/Book.tsx
  src/views/Video/VideoDelete.tsx
Labels: 💄 Design, 🐛 Fix, 😀 Merge Develop

#88 Fix: Video comment, Mobilecam usim 추가
  src/views/Camera/MobileCamera.tsx
  src/views/Video/Video.tsx
  src/views/Video/VideoDetail.tsx
Labels: 🐛 Fix, 😀 Merge Develop

#89 Fix: 비디오 정렬, 필터링 수정
  src/redux/reducer/cardReducer.ts
  src/redux/saga/cardSaga.ts
  src/redux/types.ts
  src/views/Contents/EmotionContent/EmotionContent.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
Labels: 🐛 Fix

#81 Feat: 람다 기술적 챌린지 비교(다운)
  src/services/Cam/uploadToS3Bucket.ts
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/WebCamera.tsx
Labels: ✅ Test

#91 Design: CamContent 최근영상 디자인 수정
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Contents/CamContent/WebCamContent.tsx
Labels: 💄 Design, 😀 Merge Develop

#90 Fix: USIM, 그래프, 디자인 수정
  src/views/Camera/Modal.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Emotion/EmotionLineChart.tsx
  src/views/MyPage/Edit.tsx
  src/views/MyPage/Friend/Friend.tsx
  src/views/MyPage/Friend/FriendItem.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
Labels: 💄 Design, 🐛 Fix, 😀 Merge Develop

#92 Fix: 카메라 관련 설정 수정
  src/common/constraints.ts
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/Modal.tsx
  src/views/Camera/WebCamera.tsx
  src/views/Contents/CamContent/MobileCamContent.tsx
  src/views/Emotion/Share.tsx
Labels: 🐛 Fix

#93 Fix: webcam onair버튼 비활성화 수정
  src/views/Camera/WebCamera.tsx
Labels: 💄 Design, 🐛 Fix, 😀 Merge Develop
