Repository cd-carpe-diem/Carpe-Diem-FE, pull requests merged in 2023-02, with the labels that each got.

#6 Feat: 서버로 expression value 전달
  src/webCam/index.js
Labels: ✨ Feat

#7 Chore: 수치, request url 변경
  .gitignore
  package-lock.json
  src/webCam/imgs/test.jpg
  src/webCam/index.js
Labels: 🧹Chore

#8 Merge from Feat/CD-69 to develop #7
  .gitignore
  package-lock.json
  src/webCam/imgs/test.jpg
  src/webCam/index.js
Labels: 😀 Merge Develop

#9 Feat: 영상페이지 제작
  package.json
  src/App.css
  src/App.js
  src/View/Button/OffButtons.jsx
  src/View/Button/OnButtons.jsx
  src/View/Contents/CamContent/CamContent.jsx
  src/View/Contents/VideoContent/VideoContent.jsx
  src/View/Footer/Footer.jsx
  src/View/Header/Header.jsx
  src/View/Header/MyModal.jsx
  src/View/Header/images/logotitle.png
  src/View/Header/styles.css
  src/View/Profile/Profile.jsx
  src/View/Sidebar/Sidebar.jsx
  src/View/Video/Checkbox.jsx
  src/View/Video/Video.jsx
  src/css/List.css
  src/loading.png
  src/logo.svg
  src/webCam/index.js
Labels: ✨ Feat

#10 Style: 모델 바운딩 박스 추가
  public/favicon.ico
  public/index.html
  src/webCam/index.js
Labels: 💄 Design

#11 Refactor: Front TypseScript 코드 변환
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/View/Contents/CamContent/CamContent.tsx
  src/View/Contents/PageContent/PageContent.tsx
  src/View/Contents/VideoContent/VideoContent.tsx
  src/View/Footer/Footer.jsx
  src/View/Footer/Footer.tsx
  src/View/Header/Header.jsx
  src/View/Header/Header.tsx
  src/View/Header/MyModal.tsx
  src/View/Page/Page.tsx
  src/View/Page/images/frame.png
  src/View/Profile/Profile.tsx
  src/View/Sidebar/Sidebar.tsx
  src/View/Video/Checkbox.tsx
  src/View/Video/Video.tsx
  src/custom.d.ts
  src/index.tsx
  src/reportWebVitals.tsx
  src/setupTests.tsx
  src/webCam/index.js
  tsconfig.json
Labels: ♻️ Refactor

#12 Merge from Feat/CD-74 to develop #11
  package.json
  src/App.css
  src/App.js
  src/App.test.tsx
  src/App.tsx
  src/View/Button/OffButtons.jsx
  src/View/Button/OnButtons.jsx
  src/View/Contents/CamContent/CamContent.tsx
  src/View/Contents/PageContent/PageContent.tsx
  src/View/Contents/VideoContent/VideoContent.tsx
  src/View/Footer/Footer.tsx
  src/View/Header/Header.tsx
  src/View/Header/MyModal.tsx
  src/View/Header/images/logotitle.png
  src/View/Header/styles.css
  src/View/Page/Page.tsx
  src/View/Page/images/frame.png
  src/View/Profile/Profile.tsx
  src/View/Sidebar/Sidebar.tsx
  src/View/Video/Checkbox.tsx
  src/View/Video/Video.tsx
  src/css/List.css
  src/custom.d.ts
  src/index.tsx
  src/loading.png
  src/logo.svg
  src/reportWebVitals.tsx
  src/setupTests.tsx
  src/webCam/index.js
  tsconfig.json
Labels: 😀 Merge Develop

#14 Feat: 비디오 페이지 영상 리스트 가져오기(client)
  package.json
  public/imgs/not_found_files.jpg
  public/index.html
  src/App.tsx
  src/View/Header/Header.jsx
  src/components/Header/MyModal.tsx
  src/components/Sidebar/Profile/Profile.tsx
  src/components/Sidebar/Sidebar.tsx
  src/index.tsx
  src/reducer/cardsReducer.tsx
  src/reducer/notiReducer.js
  src/store/store.js
  src/styles/App.css
  src/styles/index.css
  src/types/type.tsx
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
  src/views/Video/Video2.tsx
  tsconfig.json
Labels: ✨ Feat

#18 Feat: 웹캠 페이지 감정 실시간 차트화
  package.json
  src/views/Contents/CamContent/CamContent.tsx
  src/views/webCam/Emotion.tsx
  src/views/webCam/index.tsx
Labels: ✨ Feat, 😀 Merge Develop

#19 Feat: 앨범 삭제(client)
  public/imgs/book.jpg
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Header/MyModal.tsx
  src/config/index.ts
  src/reducer/notiReducer.js
  src/types/type.tsx
  src/views/Album/AlbumSinglePage.tsx
  src/views/Contents/LibraryContent/LibraryContent.tsx
  src/views/Contents/albumContent/AlbumSingleContent.tsx
  src/views/Library/Book.tsx
  src/views/Library/Library.tsx
  src/views/Video/Video.tsx
Labels: ✨ Feat

#20 Feat: 단일 페이지 삭제 및 FE 코드 합침
  package.json
  src/components/Footer/Footer.tsx
  src/components/Sidebar/Sidebar.tsx
  src/views/Album/AlbumMultiPage.tsx
  src/views/Album/AlbumSinglePage.tsx
  src/views/Album/Slider.tsx
  src/views/Album/UpdateSlider.tsx
  src/views/Contents/AlbumContent/EditAlbum.tsx
  src/views/Contents/VideoContent/VideoContent.tsx
  src/views/Contents/albumContent/AlbumMutiContent.jsx
  src/views/Contents/albumContent/AlbumSingleContent.tsx
  src/views/Library/Library.tsx
  src/views/Video/Video.tsx
  src/views/webCam/index.tsx
Labels: ✨ Feat, 😀 Merge Develop

#22 Design: 단일페이지& Footer 글꼴 수정
  src/App.tsx
  src/assets/frame.png
  src/styles/App.css
  src/views/Album/AlbumMultiPage.tsx
  src/views/Album/AlbumSinglePage.tsx
  src/views/Album/frame12.png
  src/views/Contents/PageContent/PageContent.tsx
  src/views/Page/Page.tsx
Labels: 💄 Design, 😀 Merge Develop

#23 Feat: 저장 & 공유
  public/index.html
  src/react-app-env.d.ts
  src/reducer/cardsReducer.tsx
  src/views/Album/AlbumSinglePage.tsx
  src/views/Album/Share.tsx
  src/views/Video/Video.tsx
Labels: ✨ Feat

#25 Feat: 앨범 전체 리스트 가져오기 & 사용자 얼굴 이미지 S3에서 다운로드
  package.json
  src/App.tsx
  src/common/constraints.ts
  src/components/Header/MyModal.tsx
  src/index.tsx
  src/reducer/cardsReducer.tsx
  src/redux/reducer/albumReducer.ts
  src/redux/reducer/index.ts
  src/redux/reducer/notiReducer.js
  src/redux/saga/albumSaga.ts
  src/redux/saga/index.ts
  src/redux/types.ts
  src/services/Cam/loadUsim.ts
  src/store/store.js
  src/store/store.ts
  src/views/Album/AlbumCarousel.tsx
  src/views/Album/AlbumMultiPage.tsx
  src/views/Camera/index.tsx
  src/views/Library/Library.tsx
  src/views/Video/Video2.tsx
Labels: ✨ Feat

#27 Feat: 소셜 로그인 버튼 구현
  package.json
  src/App.tsx
  src/components/Sidebar/Sidebar.tsx
  src/services/Cam/uploadToS3Bucket.ts
  src/views/Auth/index.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/index.tsx
  src/views/Contents/CamContent/CamContent.tsx
Labels: ✨ Feat

#26 Feat: 본 녹화 5초전 영상 추가
  src/services/Cam/sub1UploadToS3Bucket.ts
  src/services/Cam/sub2UploadToS3Bucket.ts
  src/views/Camera/index.tsx
Labels: ✨ Feat

#28 Feat: 원격 카메라 페이지 추가
  public/index.html
  src/components/Sidebar/Sidebar.tsx
  src/views/Camera/RemoteCamera.tsx
Labels: ✨ Feat

#29 Merge from Feat/CD-74 to develop #28
  public/index.html
  src/components/Sidebar/Sidebar.tsx
  src/views/Camera/RemoteCamera.tsx
Labels: 😀 Merge Develop

#30 Feat:커스텀 앨범 생성
  package.json
  src/App.tsx
  src/assets/logo512.png
  src/components/Sidebar/Sidebar.tsx
  src/styles/App.css
  src/views/Album/AlbumCarousel.tsx
  src/views/Album/AlbumMultiPage.tsx
  src/views/Album/AlbumSinglePage.tsx
  src/views/Contents/albumContent/AlbumMutiContent.jsx
  src/views/Library/Library.tsx
  src/views/Login/Login.tsx
  src/views/Main/ Parallax.tsx
  src/views/Main/parallax.css
  src/views/Video/Checkbox.tsx
  src/views/Video/Video.tsx
Labels: ✨ Feat

#31 Change: Card API 로그인 이후 서비스 이용 가능하도록 수정 [Read, Update, Delete]
  src/config/index.ts
  src/views/Album/AlbumSinglePage.tsx
  src/views/Video/Video.tsx
Labels: ♻️ Refactor, 🧹Chore

#35 Fix: 커스텀 앨범 수정
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Header/MyModal.tsx
  src/reducers/notiReducer.js
  src/sagas/notificationSaga
  src/store/store.ts
  src/views/Album/AlbumCarousel.tsx
  src/views/Album/AlbumSinglePage.tsx
  src/views/Library/Book.tsx
  src/views/Library/Library.tsx
  src/views/Main/Parallax.tsx
  src/views/Video/Video.tsx
Labels: 🐛 Fix, 😀 Merge Develop

#36 Fix: 앨범 수정, 삭제 오류 수정
  src/views/Album/AlbumCarousel.tsx
  src/views/Album/AlbumMultiPage.tsx
  src/views/Library/Book.tsx
  src/views/Library/BookButton.tsx
  src/views/Library/Library.tsx
  src/views/Video/Video.tsx
Labels: 🐛 Fix, 😀 Merge Develop

#37 [CRUD] Frontend 앨범 API 로그인 이후 서비스 이용 가능하도록 수정
  src/redux/saga/albumSaga.ts
  src/views/Library/Book.tsx
  src/views/Library/BookButton.tsx
  src/views/MyPage/Edit.tsx
  src/views/Video/Video.tsx
Labels: ♻️ Refactor, 🐛 Fix

#38 [CRUD] Frontend 앨범 API 로그인 이후 서비스 이용 가능하도록 수정 #37
  src/redux/saga/albumSaga.ts
  src/views/Library/Book.tsx
  src/views/Library/BookButton.tsx
  src/views/MyPage/Edit.tsx
  src/views/Video/Video.tsx
Labels: 😀 Merge Develop

#39 Fix: User API 로그인 이후 서비스 이용 가능하도록 수정
  src/views/MyPage/Edit.tsx
Labels: 🐛 Fix

#40 Fix: User API 로그인 이후 서비스 이용 가능하도록 수정 #39
  src/views/MyPage/Edit.tsx
Labels: 😀 Merge Develop

#41 Feat: 메인 페이지
  public/imgs/btn-google-signin-light-normal-web@2x.png
  public/imgs/login-page.png
  src/App.tsx
  src/components/Sidebar/Sidebar.tsx
  src/redux/reducer/notiReducer.js
  src/views/Album/AlbumCarousel.tsx
  src/views/Camera/index.tsx
  src/views/Contents/LibraryContent/LibraryContent.tsx
  src/views/Library/Library.tsx
  src/views/Login/Login.tsx
  src/views/Main/Parallax.tsx
  src/views/Main/parallax.css
Labels: ✨ Feat, 🐛 Fix

#43 Feat: 유저 이미지 받는 모달창
  package.json
  public/imgs/01.svg
  public/imgs/02.svg
  public/imgs/03.svg
  public/imgs/04.svg
  public/imgs/05.svg
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Header/MyModal.tsx
  src/redux/reducer/notiReducer.js
  src/redux/types.ts
  src/types/type.tsx
  src/views/Contents/MyContent/FriendContent.tsx
  src/views/Library/Library.tsx
  src/views/Login/Modal.tsx
  src/views/Login/uploadUserImgs.ts
  src/views/MyPage/Edit.tsx
  src/views/MyPage/Friend/Friend.tsx
  src/views/MyPage/Friend/FriendItem.tsx
  src/views/MyPage/Receive.tsx
  src/views/MyPage/Send.tsx
  src/views/MyPage/UserSearch/UserSearch.tsx
Labels: ✨ Feat

#42 Feat: 원격 카메라 연결 부분 추가
  src/App.tsx
  src/components/Footer/Footer.tsx
  src/hooks/useIntersectionObsever.tsx
  src/styles/App.css
  src/styles/index.css
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Contents/CamContent/CamContent.tsx
  src/views/Contents/albumContent/AlbumMutiContent.tsx
  src/views/Login/Login.tsx
  src/views/Main/Parallax.tsx
Labels: ✨ Feat

#44 Feat: 로그인 세션 유지 구현
  public/imgs/03.svg
  public/imgs/upload-usim-modal-01.svg
  public/imgs/upload-usim-modal-02.svg
  public/imgs/upload-usim-modal-03.svg
  public/imgs/upload-usim-modal-04.svg
  src/App.tsx
  src/components/MainLayout/MainLayout.tsx
  src/index.tsx
  src/redux/reducer/authReducer.ts
  src/redux/reducer/index.ts
  src/redux/reducer/notiReducer.ts
  src/redux/saga/authSaga.ts
  src/redux/saga/index.ts
  src/redux/types.ts
  src/services/loadUser.ts
  src/styles/App.css
  src/views/Auth/PrivateRoute.tsx
  src/views/Camera/Modal.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/index.tsx
  src/views/Contents/CamContent/CamContent.tsx
  src/views/Login/uploadUserImgs.ts
  yarn.lock
Labels: ✨ Feat, 🐛 Fix

#45 Feat : 앨범 API 로직 saga 전환
  src/redux/reducer/albumReducer.ts
  src/redux/reducer/cardReducer.ts
  src/redux/reducer/index.ts
  src/redux/saga/albumSaga.ts
  src/redux/types.ts
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/index.tsx
  src/views/Library/BookButton.tsx
Labels: ♻️ Refactor, ✨ Feat

#48 Merge from Feat/CD-146 to develop #47
  src/App.tsx
  src/redux/reducer/albumReducer.ts
  src/redux/reducer/cardReducer.ts
  src/redux/reducer/index.ts
  src/redux/saga/albumSaga.ts
  src/redux/types.ts
  src/styles/App.css
  src/views/Album/Share.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Camera/index.tsx
  src/views/Contents/VideoContent/VideoContent.tsx
  src/views/Library/BookButton.tsx
  src/views/Video/Video.tsx
  src/views/Video/Video3.tsx
  src/views/Video/VideoDelete.tsx
Labels: 😀 Merge Develop

#49 Design: 메인 페이지 디자인 수정
  public/main/btn-google-signin-light-normal-web@2x.png
  public/main/mask.jpg
  src/App.tsx
  src/styles/App.css
  src/views/Login/Login.tsx
  src/views/Main/Parallax.tsx
  src/views/Main/main.css
  src/views/Main/main.tsx
  src/views/Main/parallax.css
Labels: 💄 Design, 😀 Merge Develop

#53 페이지네이션(무한 스크롤)-카드 API 기능 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .yarnrc.yml
  package.json
  src/index.tsx
  src/types/custom.d.ts
  src/views/Camera/MobileCamera.tsx
  src/views/Camera/RemoteCamera.tsx
  src/views/Video/Video.tsx
  yarn.lock
Labels: 😀 Merge Develop
